services:
  - type: web
    name: ruretse-weather
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python startup.py && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"