services:
  - type: web
    name: weather-forecast
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
